import type { PostWithAuthor, Profile } from "@/types";

// Demo profiles that appear when the database has no users to suggest
export const DEMO_PROFILES: Profile[] = [
  {
    id: "demo-1",
    user_id: "demo-user-1",
    username: "sarah_codes",
    display_name: "Sarah Chen",
    bio: "Full-stack developer. React & TypeScript enthusiast. Building cool stuff one commit at a time 🚀",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    location: "San Francisco, CA",
    website: "https://sarahchen.dev",
    github_url: "https://github.com/sarahchen",
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "demo-2",
    user_id: "demo-user-2",
    username: "marco_dev",
    display_name: "Marco Rivera",
    bio: "Backend engineer @ startup. Rust, Go, and distributed systems. Coffee addict ☕",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=marco",
    location: "Berlin, Germany",
    website: "",
    github_url: "https://github.com/marcorivera",
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "demo-3",
    user_id: "demo-user-3",
    username: "priya.js",
    display_name: "Priya Sharma",
    bio: "Frontend dev obsessed with animations and DX. Open source contributor 💜",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    location: "London, UK",
    website: "https://priya.dev",
    github_url: "https://github.com/priyasharma",
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "demo-4",
    user_id: "demo-user-4",
    username: "alexbuilds",
    display_name: "Alex Kim",
    bio: "Indie hacker building in public. Ship fast, learn faster 🛠️",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    location: "Seoul, South Korea",
    website: "https://alexkim.io",
    github_url: "https://github.com/alexkim",
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
];

// Demo posts shown when the feed is empty
export const DEMO_POSTS: PostWithAuthor[] = [
  {
    id: "demo-post-1",
    user_id: "demo-user-1",
    content: "Just migrated our entire frontend from Create React App to Vite. Build times went from 45s to 3s. If you haven't switched yet, what are you waiting for? 🚀",
    link_url: "",
    likes_count: 24,
    comments_count: 8,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    profiles: DEMO_PROFILES[0],
    user_has_liked: false,
    user_has_bookmarked: false,
  },
  {
    id: "demo-post-2",
    user_id: "demo-user-2",
    content: "Hot take: Most microservices architectures would be better as a well-structured monolith. Fight me in the comments 😤\n\nSeriously though — the complexity overhead is rarely worth it at small scale.",
    link_url: "",
    likes_count: 42,
    comments_count: 15,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    profiles: DEMO_PROFILES[1],
    user_has_liked: false,
    user_has_bookmarked: false,
  },
  {
    id: "demo-post-3",
    user_id: "demo-user-3",
    content: "Made a tiny CSS trick that saved me hours: instead of calculating exact pixel values for responsive layouts, use clamp() with viewport units.\n\nfont-size: clamp(1rem, 2.5vw, 1.5rem);\n\nGame changer. ✨",
    link_url: "",
    likes_count: 37,
    comments_count: 6,
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    profiles: DEMO_PROFILES[2],
    user_has_liked: false,
    user_has_bookmarked: false,
  },
  {
    id: "demo-post-4",
    user_id: "demo-user-4",
    content: "Week 12 of building in public:\n\n📈 1,200 users\n💰 $800 MRR\n🐛 47 bugs fixed\n☕ 84 cups of coffee\n\nThe grind is real but so is the progress. Keep shipping! 🚢",
    link_url: "",
    likes_count: 56,
    comments_count: 12,
    created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    profiles: DEMO_PROFILES[3],
    user_has_liked: false,
    user_has_bookmarked: false,
  },
  {
    id: "demo-post-5",
    user_id: "demo-user-1",
    content: "TIL: You can use TypeScript's satisfies operator to validate a type without widening it. This is incredibly useful for config objects where you want autocomplete AND strict typing.\n\nconst config = { port: 3000 } satisfies ServerConfig;",
    link_url: "",
    likes_count: 19,
    comments_count: 4,
    created_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    profiles: DEMO_PROFILES[0],
    user_has_liked: false,
    user_has_bookmarked: false,
  },
];

// Demo "most active" users derived from demo posts
export const DEMO_ACTIVE_USERS = [
  { profile: DEMO_PROFILES[3], postCount: 3, totalLikes: 56 },
  { profile: DEMO_PROFILES[1], postCount: 2, totalLikes: 42 },
  { profile: DEMO_PROFILES[2], postCount: 2, totalLikes: 37 },
  { profile: DEMO_PROFILES[0], postCount: 4, totalLikes: 43 },
];
